### ISSUE TITLE
It does not scroll when nested in a ScrollView.

### ISSUE THREAD

**Issue by zhen1007** [omahili/react-native-reorderable-list#11]
Thank you for the amazing library!

My problem happens when the ReorderableList is nested inside a ScrollView.
I have to nest 3 lists into a ScrollView. But it doesn't scroll at all.
How can I make it work?

Edit: It would be great if Jared can provide the working example as described in this [issue](https://github.com/omahili/react-native-reorderable-list/issues/2#issuecomment-1084355456)

**Comment by omahili** [comment]
Thank you @zhen1007! Unforturnately at the moment it's not supported out of the box. However it's on the roadmap and I have a few ideas I want to try out soon. I just released 0.5.0, feel free to play with it and see if you can get it to work.

**Comment by omahili** [comment]
Closed in favor of https://github.com/omahili/react-native-reorderable-list/issues/2.

**Comment by omahili** [comment]
Nested lists are now supported in v0.7.0 🎉! Checkout the [examples](https://github.com/omahili/react-native-reorderable-list/tree/master/example) to see how to use them.
