### ISSUE TITLE
[Bug] pressed item stuck in dragging state on just press without moving

### ISSUE THREAD

**Issue by zarv1k** [omahili/react-native-reorderable-list#14]
Hi!

In 0.5.1 version #13 is fixed, but the fix causes a new bug: pressed item w/o actually dragging it just stuck in "dragging" state. And it resets only after it actually has dragged.

## Steps to reproduce:
Just press and release the draggable item without actually dragging it.

### Expected behaviour:
pressed item releases and resets visually w/o opacity and scale (like in 0.5.0 version):

https://github.com/user-attachments/assets/c12f7e3b-cbea-4681-952a-73b919ccfeac

### Actual behavior:
pressed item stuck in dragging state after you release your finger (has opacity, and scale) until you actually drag it:

https://github.com/user-attachments/assets/bef2d287-f946-4c8a-a74e-3fb5e1e204fb

Could you please take a look?

Thank you

**Comment by omahili** [comment]
Fixed in 0.6.0.

**Comment by omahili** [comment]
Fixed in v0.6.1.

**Comment by zarv1k** [comment]
@omahili thank you! Just tested 0.6.1 - everything works like a charm.
