### ISSUE TITLE
Please consume ReorderableList context within its provider.

### ISSUE THREAD

**Issue by narendratailwnd** [omahili/react-native-reorderable-list#16]
i was did same thing as you mention in example but still above error is came.

please look my code below. let me know if i did anything wrong.

import ReorderableList, {
  reorderItems,
  useReorderableDrag,
} from 'react-native-reorderable-list';
function app(){

 const drag = useReorderableDrag();

 const renderItem = (params) => {
    return (
      <TouchableOpacity
        onLongPress={drag}
        delayLongPress={150}
        style={[
          {
            width: 100,
            alignItems: 'center',
            justifyContent: 'center',
          },
        ]}
      >
        <Text style={{ fontSize: 24 }}>{params.item.label}</Text>
      </TouchableOpacity>
    );
  };
  const handleReorder = ({ from, to }) => {
    console.log(`Reorder`, from, to);
    const newData = reorderItems(orderList, from, to);
    setOrderList(newData);
  };

return ( <GestureHandlerRootView>
            <ReorderableList
              data={orderList}
              onReorder={handleReorder}
              renderItem={renderItem}
              keyExtractor={(item) => item.bookId}
            />
          </GestureHandlerRootView>)

**Comment by narendratailwnd** [comment]
i was found solution in other example thank you.

**Comment by omahili** [comment]
`useReorderableDrag` hook can only be used in the item component and will throw outside. For example:

```
const Card: React.FC<CardProps> = React.memo(({id, color, height}) => {
  const drag = useReorderableDrag();

  return (
    <ReorderableListItem>
      <Pressable style={[styles.card, {height}]} onLongPress={drag}>
        <Text style={[styles.text, {color}]}>Card {id}</Text>
      </Pressable>
    </ReorderableListItem>
  );
});
```

Closing, feel free to reopen if you still have issues.
