### ISSUE TITLE
Component nested in a scrollview

### ISSUE THREAD

**Issue by jared-94** [omahili/react-native-reorderable-list#2]
First thank you for your nice lib !

My problem appears when ReorderableList is nested inside a scrollview.
It works fine if the parent is not scrolled but as soon as we scroll, the drag mechanism is unusable, probably because the position of ReorderableList changed.

Do you have an idea to solve this ?

**Comment by omahili** [comment]
Sorry for the late response, I think I missed your issue.

From your explanation I think it's due to the fact that when the parent ScrollView is scrolled then it takes precedence over the gestures of the reorderable list which doesn't respond anymore. I will test it and let you know.

**Comment by jared-94** [comment]
I solved my problem with something like that

```
const enableScroll = (value) => {
   scrollViewRef.current?.setNativeProps?.({ scrollEnabled: value });
}

const onMomentumScrollEnd = (e) => {
  listRef.current?.setYoffset?.(e.nativeEvent.contentOffset.y);
}

const onEndDrag = () => {
   enableScroll(true);
   listRef.current?.setMinDist?.(50)
}

return (
  <ScrollView ref={(ref) => scrollViewRef.current = ref} onMomentumScrollEnd={onMomentumScrollEnd} >
    <Something />
    <ReorderableList
                      ref={(ref) => listRef.current = ref}
                      data={data}
                      renderItem={(renderProps) => (
                         <Pressable onPressIn={(pressProps) => {
                              listRef.current?.setMinDist?.(0);
                              drag(pressProps);
                              enableScroll?.(false);
                            }} style={{ width: 30, height: 30 }} >
                              <MyDraggableItem />
                           </Pressable>
                       )}
                    onReorder={setNewData}
                    keyExtractor={(i) => `${i.id}`}
                    dragScale={1.025}
                    bounces={false}
                    onEndDrag={onEndDrag}
     />
    <OtherThings />
  </ScrollView>
);
```

**Comment by zhen1007** [comment]
Hi @omahili Any update on this?
I want to use 3 Reorderable Lists nested in a single ScrollView.

**Comment by zhen1007** [comment]
> I solved my problem with something like that
> 
> ```
> const enableScroll = (value) => {
>    scrollViewRef.current?.setNativeProps?.({ scrollEnabled: value });
> }
> 
> const onMomentumScrollEnd = (e) => {
>   listRef.current?.setYoffset?.(e.nativeEvent.contentOffset.y);
> }
> 
> const onEndDrag = () => {
>    enableScroll(true);
>    listRef.current?.setMinDist?.(50)
> }
> 
> return (
>   <ScrollView ref={(ref) => scrollViewRef.current = ref} onMomentumScrollEnd={onMomentumScrollEnd} >
>     <Something />
>     <ReorderableList
>                       ref={(ref) => listRef.current = ref}
>                       data={data}
>                       renderItem={(renderProps) => (
>                          <Pressable onPressIn={(pressProps) => {
>                               listRef.current?.setMinDist?.(0);
>                               drag(pressProps);
>                               enableScroll?.(false);
>                             }} style={{ width: 30, height: 30 }} >
>                               <MyDraggableItem />
>                            </Pressable>
>                        )}
>                     onReorder={setNewData}
>                     keyExtractor={(i) => `${i.id}`}
>                     dragScale={1.025}
>                     bounces={false}
>                     onEndDrag={onEndDrag}
>      />
>     <OtherThings />
>   </ScrollView>
> );
> ```

Hi @jared-94 
Do you mind if you share the working example?

**Comment by omahili** [comment]
This is a work in progress, I will release it with the next version. Will keep you posted here.

**Comment by omahili** [comment]
Nested lists are now supported in v0.7.0 🎉! Checkout the [examples](https://github.com/omahili/react-native-reorderable-list/tree/master/example) to see how to use them.
