### ISSUE TITLE
Autoscroll not working

### ISSUE THREAD

**Issue by hirbod** [omahili/react-native-reorderable-list#4]
Hi,

I am using your awesome list (the smoothest out there) inside a TabBar (and also do have Statusbar + Nav header) and I've also added `ListHeaderComponent` to the Flatlist.

I think your lib only works in a plain naked view without any header, bottom tabs and ListHeaderComponent.
Autoscroll is not working correctly. Everything else is working super smooth though.

Could you have a look at this? I would love to sponsor this feature if you can fix it quickly.

This is currently on iOS, I haven't tested Android yet but I will.

**Comment by hirbod** [comment]
@omahili I made you a quick video showing the issue. This example is even without a bottom tab.

https://user-images.githubusercontent.com/504909/162582525-5b073915-8deb-43b7-8bfa-991810bc2368.mp4

**Comment by omahili** [comment]
Hi @hirbod, thank you for the appreciation!

Could you provide a minimum reproducible example of this bug, so I can test it?

**Comment by hirbod** [comment]
Hi @omahili

thanks for your answer. I will build you an example today.

**Comment by hirbod** [comment]
Hi @omahili,

sorry for the delay, was caught up in work. I created the repro.
https://github.com/hirbod/autoscroll-issue-react-native-reorderable-list

I also created an Expo Snack (with the same requirements as in your README, but this is not even working at all)
https://snack.expo.dev/@hirbod/autoscroll-issue

But the Git reproduction is working as expected but with said auto scroll issue 
(barely scrolling, sometimes not scrolling/not recognizing when to start scrolling, like in the video).

I've added a README for you inside the repo.

# Reproduction

1. Clone repository https://github.com/hirbod/autoscroll-issue-react-native-reorderable-list.git
2. Run `yarn` to install everything
3. Install `expo-cli` globally (`npm install -g expo-cli`)
4. Run `expo start` in your Root and scan the QR
   or search in your network with the `Expo Go` App (available in Apple and Play Store)

If you prefer to run a bare react-native project, just hit `expo eject` and it will create iOS and Android folders which you can use with react-native CLI OOTB.

I just added explanation here since I am not aware if you have used Expo before.

- Tested with REA 2.2.0, 2.3.1, 2.5.0 and 2.7.0.
- Tested with RNGH 1.3.0, 2.2.0, 2.3\*

The result was always the same. Autoscrolling not working correctly, even without a `ListHeaderComponent` 

FYI: I also tried a JS-navigation stack (instead of the native-stack), but that didn't make any difference.

**Comment by hirbod** [comment]
@omahili i just tested Android and its working great. So this issue is indeed an iOS only problem

**Comment by omahili** [comment]
Ok, thank you for going deep into it. I'll investigate this!

**Comment by hirbod** [comment]
Hi mate, any update on this? :)

**Comment by omahili** [comment]
I'm working on the next version which will include a fix for this. I should release it this week.

**Comment by omahili** [comment]
Fixed in #7 and released with version 0.4.0

**Comment by hirbod** [comment]
This are good news!! Going to give it a try today, thanks for your efforts so far :).

**Comment by hirbod** [comment]
@omahili thanks a ton for this. Working GREAT! Nice.
