### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by nandorojo** [omahili/react-native-reorderable-list#5]
It would be interesting if we could put items anywhere inside of a scrollview rather than in a flatlist:

```tsx
const scrollRef = useAnimatedRef()

<Animated.ScrollView ref={scrollRef}>
  <Reorder scrollRef={scrollRef} items={items} onSetItems={setItems}>
    {items.map(item => <Reorder.Item key={item} />)}
  </Reorder>
</Animated.ScrollView>
```

That's some pseudo-code inspired by `framer-motion`'s `Reorder` component. We could pass the scroll ref to the component and not have to worry about list header and footer components, which are bad for general composability. 

All good if this is too challenging, figured I'd mention it in case. Feel free to close if it feels out of scope.

**Comment by omahili** [comment]
Hi @nandorojo, this is something I'm taking into consideration and `simultaneousHandlers` could help achieving this.

**Comment by omahili** [comment]
Hi @nandorojo, I'm taking into consideration the possibility to allow nesting it into a ScollView and `simultaneousHandlers` could help achieving this. 
However I think that not using a FlatList could be counterproductive for performance reasons, so I'd stick with it.
Thank you for the proposal!

**Comment by omahili** [comment]
Closing in favor of #2
